config/routes.rb
ReviseYourToeic::Application.routes.draw do

  mount TolkEngine::Engine => '/tolk_engine', :as => 'tolk_engine'

  devise_for :translators, :controllers => { :registrations => 'tolk_engine/custom_devise/registrations', :sessions => 'tolk_engine/custom_devise/sessions' }, :class_name => 'TolkEngine::Translator', :module => :devise

  resources :originals

  resources :locales

  resources :words

  match 'filtered_words/:expression/index_filtered' => 'filtered_words#index_filtered', :as => :index_filtered
  match 'about_me/index' => "about_me#index"

  root :to => 'home#index'

end

app/models/original.rb
# == Schema Information
#
# Table name: originals
#
#  id         :integer          not null, primary key
#  path       :string(255)
#  base       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Original < ActiveRecord::Base
  attr_accessible :base
  attr_accessible :path
end

app/controllers/originals_controller.rb
class OriginalsController < ApplicationController
  # GET /originals
  # GET /originals.json
  def index
    @originals = Original.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @originals }
    end
  end

  # GET /originals/1
  # GET /originals/1.json
  def show
    @original = Original.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @original }
    end
  end

  # GET /originals/new
  # GET /originals/new.json
  def new
    @original = Original.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @original }
    end
  end

  # GET /originals/1/edit
  def edit
    @original = Original.find(params[:id])
  end

  # POST /originals
  # POST /originals.json
  def create
    @original = Original.new(params[:original])

    respond_to do |format|
      if @original.save
        format.html { redirect_to @original, notice: 'Original was successfully created.' }
        format.json { render json: @original, status: :created, location: @original }
      else
        format.html { render action: "new" }
        format.json { render json: @original.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /originals/1
  # PUT /originals/1.json
  def update
    @original = Original.find(params[:id])

    respond_to do |format|
      if @original.update_attributes(params[:original])
        format.html { redirect_to @original, notice: 'Original was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @original.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /originals/1
  # DELETE /originals/1.json
  def destroy
    @original = Original.find(params[:id])
    @original.destroy

    respond_to do |format|
      format.html { redirect_to originals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/originals_helper.rb
module OriginalsHelper
end

app/views/originals/_form.html.erb
<%= form_for(@original) do |f| %>
  <% if @original.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@original.errors.count, "error") %> prohibited this original from being saved:</h2>

      <ul>
      <% @original.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :base %><br />
    <%= f.text_field :base %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/originals/edit.html.erb
<h1>Editing original</h1>

<%= render 'form' %>

<%= link_to 'Show', @original %> |
<%= link_to 'Back', originals_path %>

app/views/originals/index.html.erb
<h1>Listing originals</h1>

<table>
  <tr>
    <th>Path</th>
    <th>Base</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @originals.each do |original| %>
  <tr>
    <td><%= original.path %></td>
    <td><%= original.base %></td>
    <td><%= link_to 'Show', original %></td>
    <td><%= link_to 'Edit', edit_original_path(original) %></td>
    <td><%= link_to 'Destroy', original, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Original', new_original_path %>

app/views/originals/new.html.erb
<h1>New original</h1>

<%= render 'form' %>

<%= link_to 'Back', originals_path %>

app/views/originals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @original.path %>
</p>

<p>
  <b>Base:</b>
  <%= @original.base %>
</p>


<%= link_to 'Edit', edit_original_path(@original) %> |
<%= link_to 'Back', originals_path %>