config/routes.rb
ReviseYourToeic::Application.routes.draw do

  mount TolkEngine::Engine => '/tolk_engine', :as => 'tolk_engine'

  devise_for :translators, :controllers => { :registrations => 'tolk_engine/custom_devise/registrations', :sessions => 'tolk_engine/custom_devise/sessions' }, :class_name => 'TolkEngine::Translator', :module => :devise

  resources :originals

  resources :locales

  resources :words

  match 'filtered_words/:expression/index_filtered' => 'filtered_words#index_filtered', :as => :index_filtered
  match 'about_me/index' => "about_me#index"

  root :to => 'home#index'

end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id          :integer          not null, primary key
#  english     :string(255)
#  french      :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  path        :string(255)
#  original_id :integer
#

class Word < ActiveRecord::Base
  attr_accessible :english
  attr_accessible :french

  belongs_to :original

  delegate :path, :to => :original
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    @vocabulary = YmlLoader.load_yaml_vocabulary_shit

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end



  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for @word, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :english, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :english, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :french, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :french, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :locale, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :locale, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lvl1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lvl1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lvl2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lvl2, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                words_path, :class => 'btn' %>
  </div>
<% end %>

app/views/words/edit.html.erb
<%- model_class = @word.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/words/index.html.haml
- model_class = Word.new.class
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:english)
      %th= model_class.human_attribute_name(:french)
      / %th= model_class.human_attribute_name(:path)
      / %th= model_class.human_attribute_name(:original_id)
      / %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @words.each do |word|
      %tr
        %td= link_to word.id, word_path(word)
        %td= word.english.humanize
        %td= word.french.humanize
        / %td= word.original.path
        / %td= word.original_id
        / %td= word.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), |
            edit_word_path(word), :class => 'btn btn-mini'           |
          -#
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                  |
            word_path(word),                                                                                |
            :method => :delete,                                                                             |
            :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), |
            :class => 'btn btn-mini btn-danger'                                                             |

app/views/words/new.html.erb
<%- model_class = @word.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/words/show.html.erb
<%- model_class = @word.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:english) %>:</strong></dt>
  <dd><%= @word.english %></dd>
  <dt><strong><%= model_class.human_attribute_name(:french) %>:</strong></dt>
  <dd><%= @word.french %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locale) %>:</strong></dt>
  <dd><%= @word.locale %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lvl1) %>:</strong></dt>
  <dd><%= @word.lvl1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lvl2) %>:</strong></dt>
  <dd><%= @word.lvl2 %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              words_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_word_path(@word), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              word_path(@word),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>