config/routes.rb
ReviseYourToeic::Application.routes.draw do

  mount TolkEngine::Engine => '/tolk_engine', :as => 'tolk_engine'

  devise_for :translators, :controllers => { :registrations => 'tolk_engine/custom_devise/registrations', :sessions => 'tolk_engine/custom_devise/sessions' }, :class_name => 'TolkEngine::Translator', :module => :devise

  resources :originals

  resources :locales

  resources :words

  match 'filtered_words/:expression/index_filtered' => 'filtered_words#index_filtered', :as => :index_filtered
  match 'about_me/index' => "about_me#index"

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReviseYourToeic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %title= content_for?(:title) ? yield(:title) : "ReviseYourToeic"
        = csrf_meta_tags
        / Le HTML5 shim, for IE6-8 support of HTML elements
        /[if lt IE 9]
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "style_for_flip", :media => "all"
        %link{:href => "images/favicon.ico", :rel => "shortcut icon"}
          %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}
            %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
              %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_path} Revise my English Test
          .container.nav-collapse
            %ul.nav
              %li
                = link_to words_path do
                  .icon-th-list
                  = t("words")
              %li
                = link_to about_me_index_path do
                  .icon-user
                  = t("about_me")
              %li
                = link_to tolk_engine_path do
                  .icon-globe
                  = t("internationalizer")
          / /.nav-collapse
    .container
      .content
        .row
          .span9
            .hero-unit
              = yield
          .span3
            .well.sidebar-nav
              %h3 Catégorie
              %ul.nav.nav-list
                = raw(@liste_without_key_2)

              / = raw(@liste_without_key)
            / /.well
          / /span
        / /row
      / /content
      %footer
        .pagination-centered
          .row
            .span9
              = link_to image_tag("twitter.png"), "https://twitter.com/huet_vincent"
              = link_to image_tag("facebook.png"), "https://twitter.com/vincent.alex.huet"
              = link_to image_tag("google.png"), "v.huet@groupe-esigelec.fr"
              = link_to image_tag("linkedin.png"), "https://linkedin.com/huet_vincent"
          %br
          .row
            .span9
              %strong
                %a{:href => "https://twitter.com/huet_vincent"} © Vincent Huet
              Initiative & Imagination 2012
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"